id: DEEBDA5F1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:19:42+00:00'
last_modified: '2022-05-27T05:56:06.726238+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    5f4e:
      image_group_id: I1PD95902
      title: སྲིད་པ་འཕོ་བ།
      total_pages: 1605
      order: 57
      base_file: 5f4e.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
