id: 68ab6b038e3e425e841936f0873dbc0f
initial_creation_type: ocr
source_metadata:
  volumes:
    5ef7c9a4669e4003be78f085c2f3aa44:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: ''
      total_pages: 1605
      volume_number: 57
